### PR TITLE
WIP: Add typescript types 

### PR DESCRIPTION
**Pull request by mistlog**
see https://github.com/bestguy/sveltestrap/issues/129

### CODE REVIEW

**Comment by bestguy** [comment]
I mentioned in linked issue, but @BlackFenix2 , seems like we could use reactstrap's types as a starting point/copy? https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/reactstrap/lib

With property attribution of course.  The props are almost identical, even though that is for a React library.

**Comment by BlackFenix2** [comment]
@bestguy yeah, we can pretty much copy the type definition files and modify for svelte as needed. I would have to make another PR since this one is 4 months old. I can do this in the morning and link this PR to continue the thread.

**Comment by BlackFenix2** [comment]
wait a sec, what if we rewrote the svelte components to utilize typescript instead? appending each script tag would be easier than copying separate type definition files. i already know how to set rollup to process typescript syntax,

**Comment by BlackFenix2** [comment]
@bestguy  forgots to mention, i forked the branch and should have a PR up soon.

**Comment by bestguy** [comment]
I'd be up for that, but a big change so assumed d.ts was easier.  If it's straightforward, maybe if you could share the rollup config and we all could convert incrementally?

**Comment by BlackFenix2** [comment]
not gonna be straightforward i'm afraid, i have to bump some of the rollup plugins with their newer packages (rollup-plugin-commonjs is now @rollup/plugin-commonjs). ill PR the bump first without typescript just to get the project as a whole up to date.

**Pull request closed without merging**
