### PR TITLE
feat(dropdown): add support for auto close functionality

### PR DESCRIPTION
**Pull request by dysfunc**
This changes add support for the dropdown auto close behavior described [here](https://getbootstrap.com/docs/5.0/components/dropdowns/#auto-close-behavior) via `autoClose` attribute. This supports all the cases: `default`, `manual`, `inside`, and `outside`.

#297

### CODE REVIEW

**Comment by sidvora** [comment]
+1

**Comment by amit777** [comment]
+1, thanks!

**Comment by dysfunc** [comment]
@bestguy can this be merged? I need this functionality for several different components I've been working on.

**Review by bestguy — APPROVED** [review]
Great, thank you!

**Pull request merged**
