### PR TITLE
Fix popperjs import for SvelteKit Patch-2

### PR DESCRIPTION
**Pull request by laxadev**
I was still faced with this issue #463 after fetched the latest fix #356 
I made a fix in two more files.

### CODE REVIEW

**Review by benmccann — CHANGES_REQUESTED** [review]
Oh goodness. This isn't a fix at all. It just reverts the last PR. Let me test again and see what the issue is

**Comment by benmccann** [comment]
I sent a fix here: https://github.com/bestguy/sveltestrap/pull/566

**Comment by laxadev** [comment]
> I sent a fix here: #566

@benmccann What is the difference between this PR and yours?

**Comment by benmccann** [comment]
Oops! I looked at this too quickly originally. Yes, your fix is the same as mine. Sorry about that. The issue description in my PR will close some linked issues with the magic "fixes" and "closes" keywords. If you want to copy that into your PR description (it doesn't work in comments, but only by editing the description) I can go ahead and close my PR

**Comment by laxadev** [comment]
@benmccann No worries. Let's keep yours and I'm going to close this one. Thanks.

**Pull request closed without merging**
