### PR TITLE
Bump major versions

### PR DESCRIPTION
**Pull request by BlackFenix2**
Good news, i updated all the node packages to the latest versions and the storybook demo/build works perfectly.

Bad news, i might of broken jest :(. something to do with clsx maybe? im stumped here.

i still have my fork, any assistance with the mild jest issue would be appreciated. otherwise everything else works.

```cmd
 Badge › should render link with href

    TypeError: clsx is not a function

      10 | 
      11 | 
    > 12 |   $: classes = clsx(
         |              ^
      13 |     className,

      at Object.$$self.$$.update (src/Badge.svelte:12:14)
      at init (node_modules/svelte/internal/index.js:1446:8)
      at render (node_modules/@testing-library/svelte/dist/pure.js:71:21)
      at Object.<anonymous> (src/__test__/Badge.spec.js:33:27)


```
```svelte
<script>
  import clsx from 'clsx';

  let className = '';
  export { className as class };
  export let children = undefined;
  export let color = 'secondary';
  export let href = undefined;
  export let pill = false;


  $: classes = clsx(
    className,
    'badge',
    `badge-${color}`,
    pill ? 'badge-pill' : false
  );
</script>

{#if href}
  <a {...$$restProps} {href} class={classes}>
    {#if children}
      {children}
    {:else}
      <slot />
    {/if}
  </a>
{:else}
  <span {...$$restProps} class={classes}>
    {#if children}
      {children}
    {:else}
      <slot />
    {/if}
  </span>
{/if}

```

### CODE REVIEW

**Comment by bestguy** [comment]
Sweet!  I'll take a look at jest

**Comment by bestguy** [comment]
Hey @BlackFenix2 , not sure what's up with babel or jest here, but found that this works if I inline clsx instead of import.  Let me fix up master with this and maybe you can rebase, it seems to work fine with your changes

**Comment by bestguy** [comment]
Hi @BlackFenix2 , after a real mess sorting through the jest, node 12, ci issues, I made and merged  https://github.com/bestguy/sveltestrap/pull/163 with seems to fix issues.  

It's a bunch of interrelated changes afaik, but apologies for causing conflicting files with my merge,  if you wouldn't mind merging or rebasing from master.

**Comment by BlackFenix2** [comment]
@bestguy i merged the changes from your current master branch, my PR should be up to date now.

Jest doesnt yell at me anymore, everything is in working order! once we can get this merged ill work on typescript support.

**Comment by BlackFenix2** [comment]
ok, ill rebase the changes from your master branch and start working on a PR for Typescript support.

**Comment by bestguy** [comment]
Awesome, thanks!  I'm happy to help convert after config updates.  
One question/concern that occurs to me now is we were encouraged to include Svelte src as part of npm package to work with SSR/Sapper.  Moving to TS might mess that up?   Am unsure of the current level of Typescript support in Svelte/Sapper

**Comment by BlackFenix2** [comment]
Uncle BlackFenix2 did not forsee that complication, ill try to brainstorm a way to use typescript and support es/umd bundles. Sapper can support typescript with the correct preprocessor but i am trying to compile the typescript down to regular js, the .svelte files can be imported as-is without issue. i have to test this out extensively, ill make a skeleton PR so we can continue the conversation.

if i cannot get the typescript conversion to work, ill prob just add *.d.ts files from reactstrap.

**Comment by bestguy** [comment]
It's mostly sapper afaik, if that supports TS out of the box or at least "easily", that's not a big problem and we can document

**Pull request merged**
