### PR TITLE
Support for .row-cols-* classes in Row

### PR DESCRIPTION
**Pull request by ladeiko**

### CODE REVIEW

**Comment by bestguy** [comment]
Ah thanks @ladeiko , would you mind resolving the conflicts above?  We updated Row.svelte a few months ago

**Comment by ladeiko** [comment]
I'll try

**Review by bestguy — APPROVED** [review]
Thanks @ladeiko 
Missing the Row.d.ts changes and tests for this addition.  But I can merge this and we can before publishing new version.  You are welcome to add these if you have a chance in next few days.

**Comment by bestguy** [comment]
Actually it was quick changes and corrected here: https://github.com/bestguy/sveltestrap/pull/232
Will release new version over weekend.
Thanks for adding this!

**Comment by ladeiko** [comment]
Thanks

**Pull request merged**
