### PR TITLE
fix popper issue, fix failing tests & bump dependencies

### PR DESCRIPTION
**Pull request by kbsali**

### CODE REVIEW

**Comment by tommygiesbrecht** [comment]
Hello! Is it possible to merge this fix?
Thanks
Tommy

**Comment by kbsali** [comment]
ping @bestguy :)
Maybe it is not relevant anymore? I only see now that there has been some activity in early August, that's great news! :)
Would it be possible to add contributors with merging auth?

**Comment by bestguy** [comment]
Thanks @kbsali @tommygiesbrecht  , I really appreciate the PRs and desire to fix this for SvelteKit, but none of these fixes and forks changing to `'@popperjs/core'` correct the root issue, which is why the PRs to change popper imports have not been merged after so long.

I've tried the same in past as I mentioned, but I've been unwilling to break the [Svelte REPL](https://svelte.dev/repl/hello-world?version=3.50.1).   This is not deprecated AFAIK, and I'm a heavy user with Sveltestrap.   (I know Sapper is deprecated so I wont worry about that one any longer).

Upgrading to Floating UI won't fix this either, as they continue the `process.env` usage:  https://floating-ui.com/docs/getting-started#package-entry-points , and they have not accepted PRs in past to change this.  It's really frustrating but that is their choice.

Only solutions I can think of is:
- use something other than popper or floating-ui (please suggest if you are aware of libaries)
- Fork popper and remove process.env and use.
- Change Svelte REPL rollup config with the workaround popper suggests above.   (I can try and PR/issue there, but that repo seems even less responsive than I am! 😅)

I will gladly take any help or ideas that fixes this if it works on svelte.dev   
I really do not want to break this!

**Comment by kbsali** [comment]
This PR was addressing several long standing issues. This is old already, but if I remember well I was not even using the popperjs related component, but without the change I had issue building my project...

**Comment by bestguy** [comment]
Okay thanks, I'll cherry pick the other changes aside from the popper change.

**Comment by kbsali** [comment]
too bad PRs are ignored...

**Pull request closed without merging**
