### PR TITLE
Bug Fix Popover

### PR DESCRIPTION
**Pull request by eddie0329**
## 📌 issue

There was a bug that need double click to open popover due to focus and click event added.
In order to fix it, i remove focus and blur event.

### CODE REVIEW

**Comment by bestguy** [comment]
Thank you @eddie0329 !  Would you mind comparing the new behavior with the Bootstrap documentation?  https://getbootstrap.com/docs/5.0/components/popovers/#dismiss-on-next-click

I had added focus/blur to cover this trigger, but my implementation was bad, sorry.

**Comment by eddie0329** [comment]
> Thank you @eddie0329 ! Would you mind comparing the new behavior with the Bootstrap documentation? https://getbootstrap.com/docs/5.0/components/popovers/#dismiss-on-next-click
> 
> I had added focus/blur to cover this trigger, but my implementation was bad, sorry.

Hello @bestguy . Do i have to implement dissmisable popover all the time? Or should user can control it?

**Comment by bestguy** [comment]
Good question @eddie0329 , let me see what the best default is here.  It seems like tag choice matters, but not sure if that helps us.  Will look closer this weekend.

**Comment by bestguy** [comment]
Hello @eddie0329 , I think we might want to change this even further.  Can you please review #223 and let me know if would correct this issue?

**Comment by bestguy** [comment]
Corrected in #223, and published in sveltestrap@3.12.1 
Thank you @eddie0329 !

**Pull request closed without merging**
