### PR TITLE
Update to Svelte v3 (with dropdown fixes)

### LINKED ISSUE #13: Svelte v3 compatibility
Now that v3 of Svelte is out, are you interested in upgrading this library to be compatible?

I've [started a fork](https://github.com/TheBosZ/sveltestrap) to work on updating the components to be compatible with v3.

### PR DESCRIPTION
**Pull request by Renerick**
See also #15 

Closes #13 

Fixed problem with the Dropdown context in #15 with Svelte Context API (https://svelte.dev/docs#setContext). Also some minor fixes for Dropdown and Input Label

### CODE REVIEW

**Comment by Renerick** [comment]
I also allowed myself to add a new logo for the new version of the documentation

**Comment by bestguy** [comment]
Awesome!   Thank you will take a look

**Comment by bestguy** [comment]
@Renerick , this looks great and plan to merge.  One hold up is I'm not sure if the build is working correctly - I am receiving odd errors importing and using Sveltestrap components:

```
TypeError: Cannot call a class constructor without |new|
```

I am going to compare rollup config with the Svelma library (https://github.com/c0bra/svelma) which does seem to work.

**Comment by bestguy** [comment]
Ah, I found the issue.  I will merge this and PR the build changes separately.
Thank you @Renerick and @TheBosZ for this work!

**Pull request merged**
